//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPTUGWEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
        [Display(Name = "Mã đơn hàng")]
        public string MAHD { get; set; }
        [Display(Name = "Mã nhân viên")]
        public string MANV { get; set; }
        [Display(Name = "Mã khách hàng")]
        public string MAKH { get; set; }
        [Display(Name = "Ngày đặt hàng")]
        public System.DateTime TGDAT { get; set; }
        [Display(Name = "Ngày giao hàng")]
        public Nullable<System.DateTime> TGGIAO { get; set; }
        [Display(Name = "Hình thức thanh toán")]
        public int IDTHANHTOAN { get; set; }
        [Display(Name = "Đã thanh toán")]
        public bool DATHANHTOAN { get; set; }
        [Display(Name = "Đã giao hàng")]
        public bool DAGIAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual THANHTOAN THANHTOAN { get; set; }
    }
}
