//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPTUGWEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
        [Display(Name = "Mã nhân viên")]
        public string MANV { get; set; }
        [Display(Name = "Tên nhân viên")]
        public string TENNV { get; set; }
        [Display(Name = "Ngày sinh")]
        public System.DateTime NGAYSINH { get; set; }
        [Display(Name = "Điện thoại")]
        public string SDT { get; set; }
        [Display(Name = "Chức vụ")]
        public string CHUCVU { get; set; }
        [Display(Name = "Tên đăng nhập")]
        public string TENDN { get; set; }
        [Display(Name = "Mật khẩu")]
        public string MK { get; set; }
        [Display(Name = "Ảnh")]
        public string ANHNV { get; set; }
        [Display(Name = "Email")]
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
