//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPTUGWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public int MANV { get; set; }
        public string TENNV { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public string SDT { get; set; }
        public bool QTV { get; set; }
        public string TENDN { get; set; }
        public string MK { get; set; }
        public string ANHNV { get; set; }
        public string EMAIL { get; set; }
    }
}
