//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPTUGWEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTHDs = new HashSet<CTHD>();
        }

        [Display(Name = "Mã sản phẩm")]
        public string MASP { get; set; }
        [Display(Name = "Mã loại sản phẩm")]
        public string MALSP { get; set; }
        [Display(Name = "Tên sản phẩm")]
        public string TENSP { get; set; }
        [Display(Name = "Đơn vị tính")]
        public string DVT { get; set; }
        [Display(Name = "Kích thước")]
        public short KICHTHUOC { get; set; }
        [Display(Name = "Đơn giá")]
        public decimal DONGIA { get; set; }
        [Display(Name = "Mã nhà cung cấp")]
        public string MANCC { get; set; }
        [Display(Name = "Kho")]
        public int SLTON { get; set; }
        [Display(Name = "Thông tin sản phẩm")]
        public string CHITIETSP { get; set; }
        [Display(Name = "Ảnh")]
        public string ANHSP { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual LOAISP LOAISP { get; set; }
        public virtual NHACC NHACC { get; set; }
    }
}
