//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPTUGWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public string MASP { get; set; }
        public string MALSP { get; set; }
        public string TENSP { get; set; }
        public string DVT { get; set; }
        public short KICHTHUOC { get; set; }
        public decimal DONGIA { get; set; }
        public string MANCC { get; set; }
        public int SLTON { get; set; }
        public string CHITIETSP { get; set; }
        public string ANHSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual LOAISP LOAISP { get; set; }
        public virtual NHACC NHACC { get; set; }
    }
}
